title: AirPlay Security
description: AirPlay Security settings
payload:
  payloadtype: com.apple.airplay.security
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: n/a
    tvOS:
      introduced: '11.0'
      multiple: false
      supervised: false
      allowmanualinstall: true
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  content: Manages the AirPlay Security settings on Apple TV (Settings > AirPlay >
    Security). Use this payload to lock Apple TV to a particular style of AirPlay
    security. The setting can enable/disable an on-screen passcode, or require a specific
    password phrase.
payloadkeys:
- key: SecurityType
  title: Security Type
  type: <string>
  presence: required
  rangelist:
  - PASSCODE_ONCE
  - PASSCODE_ALWAYS
  - PASSWORD
  content: |-
    The security policy for AirPlay. Allowed values:

    * 'PASSCODE_ONCE': Requires an onscreen passcode on first connection from a device. Subsequent connections from the same device aren't prompted.
    * 'PASSCODE_ALWAYS': Requires an onscreen passcode for every AirPlay connection. After an AirPlay connection ends, the system allows reconnecting within 30 seconds without a password.
    * 'PASSWORD': Requires the passphrase set for 'Password'.

    'NONE' was deprecated in tvOS 11.3. Existing profiles that use 'NONE' get the 'PASSWORD_ONCE' behavior.
- key: AccessType
  title: Access Type
  type: <string>
  presence: required
  rangelist:
  - ANY
  - WIFI_ONLY
  content: |-
    The access policy for AirPlay.
    'ANY' allows connections from both Ethernet/WiFi and Apple Wireless Direct Link.
    'WIFI_ONLY' allows connections only from devices on the same Ethernet/WiFi network as Apple TV.
- key: Password
  title: Password
  type: <string>
  presence: optional
  content: The AirPlay password; required if 'SecurityType' is 'PASSWORD'.
