title: Apply Redemption Code Command
description: If a redemption code is needed during app installation, the server can
  use this command to complete the app installation.
payload:
  requesttype: ApplyRedemptionCode
  supportedOS:
    iOS:
      introduced: '5.0'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      sharedipad:
        mode: forbidden
      userenrollment:
        mode: forbidden
    macOS:
      introduced: n/a
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  content: If a redemption code is needed during app installation, the server can
    use this command to complete the app installation.
payloadkeys:
- key: Identifier
  type: <string>
  presence: required
  content: The bundle identifier of the app.
- key: RedemptionCode
  type: <string>
  presence: required
  content: The redemption code that applies to the app pending installation.
