title: Disk Management:Settings
description: Use this configuration to install disk management settings on the device.
payload:
  declarationtype: com.apple.configuration.diskmanagement.settings
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '15.0'
      allowed-enrollments:
      - supervised
      - local
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: combined
payloadkeys:
- key: Restrictions
  type: <dictionary>
  presence: optional
  content: The restrictions for the disk.
  subkeys:
  - key: ExternalStorage
    title: External Storage
    type: <string>
    presence: optional
    rangelist:
    - Allowed
    - ReadOnly
    - Disallowed
    combinetype: enum-last
    content: |-
      Specifies the mount policy for external storage:
      * 'Allowed': the system can mount external storage that is read-write or read-only.
      * 'ReadOnly': the system can only mount read-only external storage. Note that external storage that is read-write will not be mounted read-only.
      * 'Disallowed': The system can't mount any external storage.
  - key: NetworkStorage
    title: Network Storage
    type: <string>
    presence: optional
    rangelist:
    - Allowed
    - ReadOnly
    - Disallowed
    combinetype: enum-last
    content: |-
      Specifies the mount policy for network storage:
      * 'Allowed': the system can mount network storage that is read-write or read-only.
      * 'ReadOnly': the system can only mount read-only network storage. Note that network storage that is read-write will not be mounted read-only.
      * 'Disallowed': The system can't mount any network storage.
